return {
  "nvim-lua/plenary.nvim",
  "christoomey/vim-tmux-navigator",

  -- Load modular plugin configurations
  require("davic.plugins.colorscheme"),
  require("davic.plugins.neo-tree"),
  require("davic.plugins.bufferline"),
  require("davic.plugins.lualine"),
  require("davic.plugins.noice"),
  require("davic.plugins.flash"),
  require("davic.plugins.mini-pairs"),
  require("davic.plugins.todo-comments"),
  require("davic.plugins.mini-surround"),
  require("davic.plugins.which-key"),
  require("davic.plugins.trouble"),
  require("davic.plugins.dashboard"),
  require("davic.plugins.snacks"),
  require("davic.plugins.mini-diff"),
  require("davic.plugins.illuminate"),
  require("davic.plugins.mason"),
  require("davic.plugins.lspconfig"),
  require("davic.plugins.neoconf"),
  require("davic.plugins.neodev"),
  require("davic.plugins.nvim-cmp"),
  require("davic.plugins.luasnip"),
  require("davic.plugins.conform"),
  require("davic.plugins.nvim-lint"),
  require("davic.plugins.none-ls"),
  require("davic.plugins.telescope"),
  require("davic.plugins.telescope-fzf-native"),
  require("davic.plugins.telescope-ui-select"),
  require("davic.plugins.harpoon"),
  require("davic.plugins.nvim-treesitter"),
  require("davic.plugins.gitsigns"),
}
